apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"
  ELASTICSEARCH_NODE: "http://elasticsearch-service:9200"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  MIDTRANS_API_URL: "https://api.midtrans.com"
